<?php

return [
    [
        'name'         => 'Drenagem Linfática',
        'duration_min' => 60,
        'price'        => 130.00,
        'color_hex'    => '#ec4899',
        'description'  => 'Técnica com movimentos suaves que pode ajudar a reduzir o inchaço, aliviar a retenção de líquidos e promover sensação de leveza no corpo.',
        'active'       => true,
    ],
    [
        'name'         => 'Drenagem Gestante',
        'duration_min' => 60,
        'price'        => 140.00,
        'color_hex'    => '#f472b6',
        'description'  => 'Atendimento pensado para gestantes, com foco em conforto, alívio da retenção de líquidos e bem-estar durante essa fase.',
        'active'       => true,
    ],
    [
        'name'         => 'Massagem Express',
        'duration_min' => 60,
        'price'        => 100.00,
        'color_hex'    => '#22c55e',
        'description'  => 'Sessão prática para aliviar tensões do dia a dia, favorecer o relaxamento e devolver sensação de disposição em menos tempo.',
        'active'       => true,
    ],
    [
        'name'         => 'Massagem Relaxante',
        'duration_min' => 60,
        'price'        => 120.00,
        'color_hex'    => '#10b981',
        'description'  => 'Experiência voltada para desacelerar, aliviar tensões musculares e contribuir para uma sensação ampla de relaxamento e bem-estar.',
        'active'       => true,
    ],
    [
        'name'         => 'Detox / Argiloterapia',
        'duration_min' => 60,
        'price'        => 110.00,
        'color_hex'    => '#8b5cf6',
        'description'  => 'Cuidado corporal com argilas ricas em minerais, voltado para purificação da pele, remoção de impurezas e sensação renovada de equilíbrio.',
        'active'       => true,
    ],
    [
        'name'         => 'Drenagem Facial',
        'duration_min' => 40,
        'price'        => 90.00,
        'color_hex'    => '#06b6d4',
        'description'  => 'Massagem suave que estimula a circulação, reduz inchaço e promove revitalização da pele do rosto.',
        'active'       => true,
    ],
    [
        'name'         => 'Limpeza de Pele',
        'duration_min' => 60,
        'price'        => 150.00,
        'color_hex'    => '#3b82f6',
        'description'  => 'Higienização profunda com extração de cravos e aplicação de ativos para purificar e renovar a pele.',
        'active'       => true,
    ],
    [
        'name'         => 'Hidratação dos Lábios',
        'duration_min' => 30,
        'price'        => 60.00,
        'color_hex'    => '#f97316',
        'description'  => 'Tratamento hidratante e nutritivo para lábios ressecados, devolvendo maciez, volume natural e conforto.',
        'active'       => true,
    ],
    [
        'name'         => 'Revitalização Facial',
        'duration_min' => 50,
        'price'        => 160.00,
        'color_hex'    => '#eab308',
        'description'  => 'Protocolo completo com ativos revitalizantes, massagem modeladora e máscara para devolver viço e firmeza à pele.',
        'active'       => true,
    ],
    [
        'name'         => 'SPA dos Pés',
        'duration_min' => 40,
        'price'        => 85.00,
        'color_hex'    => '#14b8a6',
        'description'  => 'Experiência relaxante para os pés com banho de imersão, esfoliação, hidratação e massagem revitalizante.',
        'active'       => true,
    ],
];
