<?php

return [
    [
        'name'         => 'Drenagem Linfática',
        'duration_min' => 60,
        'price'        => 130.00,
        'color_hex'    => '#ec4899',
        'description'  => 'Técnica com movimentos suaves que pode ajudar a reduzir o inchaço, aliviar a retenção de líquidos e promover sensação de leveza no corpo.',
        'active'       => true,
    ],
    [
        'name'         => 'Massagem Gestante',
        'duration_min' => 60,
        'price'        => 130.00,
        'color_hex'    => '#f472b6',
        'description'  => 'Atendimento pensado para gestantes, com foco em conforto, alívio da retenção de líquidos e bem-estar durante essa fase.',
        'active'       => true,
    ],
    [
        'name'         => 'Massagem Relaxante',
        'duration_min' => 60,
        'price'        => 130.00,
        'color_hex'    => '#10b981',
        'description'  => 'Experiência voltada para desacelerar, aliviar tensões musculares e contribuir para uma sensação ampla de relaxamento e bem-estar.',
        'active'       => true,
    ],
    [
        'name'         => 'Pedras Quentes',
        'duration_min' => 60,
        'price'        => 140.00,
        'color_hex'    => '#ef4444',
        'description'  => 'Massagem com pedras basálticas aquecidas que proporcionam relaxamento profundo e alívio de tensões.',
        'active'       => true,
    ],
    [
        'name'         => 'Ventosaterapia',
        'duration_min' => 40,
        'price'        => 140.00,
        'color_hex'    => '#a855f7',
        'description'  => 'Técnica com ventosas que estimula a circulação sanguínea, alivia dores musculares e promove sensação de bem-estar.',
        'active'       => true,
    ],
    [
        'name'         => 'Bambuterapia',
        'duration_min' => 60,
        'price'        => 140.00,
        'color_hex'    => '#65a30d',
        'description'  => 'Massagem com bambus de diferentes diâmetros que modela o corpo, reduz medidas e alivia tensões.',
        'active'       => true,
    ],
    [
        'name'         => 'Vela Quente',
        'duration_min' => 50,
        'price'        => 140.00,
        'color_hex'    => '#f59e0b',
        'description'  => 'Massagem com óleo de vela aquecido rico em vitaminas que hidrata profundamente a pele e relaxa o corpo.',
        'active'       => true,
    ],
    [
        'name'         => 'Massagem Desportiva',
        'duration_min' => 60,
        'price'        => 150.00,
        'color_hex'    => '#3b82f6',
        'description'  => 'Massagem voltada para atletas e praticantes de atividade física que auxilia na recuperação muscular e prevenção de lesões.',
        'active'       => true,
    ],
    [
        'name'         => 'Detox Corporal',
        'duration_min' => 60,
        'price'        => 160.00,
        'color_hex'    => '#8b5cf6',
        'description'  => 'Cuidado corporal com argilas ricas em minerais, voltado para purificação da pele, remoção de impurezas e sensação renovada de equilíbrio.',
        'active'       => true,
    ],
    [
        'name'         => 'Drenagem Facial',
        'duration_min' => 40,
        'price'        => 70.00,
        'color_hex'    => '#06b6d4',
        'description'  => 'Massagem suave que estimula a circulação, reduz inchaço e promove revitalização da pele do rosto.',
        'active'       => true,
    ],
    [
        'name'         => 'Limpeza de Pele',
        'duration_min' => 60,
        'price'        => 150.00,
        'color_hex'    => '#3b82f6',
        'description'  => 'Higienização profunda com extração de cravos e aplicação de ativos para purificar e renovar a pele.',
        'active'       => true,
    ],
    [
        'name'         => 'Hidratação Labial',
        'duration_min' => 30,
        'price'        => 50.00,
        'color_hex'    => '#f97316',
        'description'  => 'Tratamento hidratante e nutritivo para lábios ressecados, devolvendo maciez, volume natural e conforto.',
        'active'       => true,
    ],
    [
        'name'         => 'Spa dos Pés',
        'duration_min' => 40,
        'price'        => 100.00,
        'color_hex'    => '#14b8a6',
        'description'  => 'Experiência relaxante para os pés com banho de imersão, esfoliação, hidratação e massagem revitalizante.',
        'active'       => true,
    ],
    [
        'name'         => 'Revitalização Facial',
        'duration_min' => 50,
        'price'        => 120.00,
        'color_hex'    => '#eab308',
        'description'  => 'Protocolo completo com ativos revitalizantes, massagem modeladora e máscara para devolver viço e firmeza à pele.',
        'active'       => true,
    ],
];
